name: Freeze
version: 1.0-SNAPSHOT
main: com.nitecell.freeze.Freeze
api-version: 1.13
authors: [Nitecell]
description: Freeze (Learning)

commands:
  freeze:
    usage: /<command>
    aliases: [ss]
    description: Freeze Command
