name: Healer
version: ${project.version}
main: com.nitecell.healer.Healer
api-version: 1.13
authors: [Nitecell]
description: Healing Plugin (Learning)

commands:
  heal:
    usage: /<command>
    aliases: [health, givehealth. givehp, hp]
    description: Heal
  feed:
    usage: /<command>
    aliases: [food, sate]
    description: Feed