name: MOTD
version: 1.0-SNAPSHOT
main: com.nitecell.motd.MOTD
api-version: 1.13
authors: [Nitecell]
description: Simple MOTD Plugin that is Not Configurable

commands:
  motd:
    usage: /<command>
    description: View the Server's MOTD
  setmotd:
    usage: /<command>
    description: Set the MOTD of the server.

permissions:
  motd.set:
    description: Uset he SetMOTD Command to change the MOTD.
    default: op