name: MOTD
version: ${project.version}
main: com.nitecell.motd.MOTD
api-version: 1.13
authors: [Nitecell]
description: Simple MOTD Plugin that is Not Configurable

commands:
  motd:
    usage: /<command>
    description: View the Server's MOTD
  setmotd:
    usage: /<command>
    description: Set the MOTD of the server.
  setservermotd:
    usage: /<command>
    description: Set the MOTD for the Server List

permissions:
  motd.*:
    description: Use all MOTD Commands
    children:
      motd.ingame.check: true
      motd.ingame.set: true
      motd.server.set: true
    default: op
  motd.ingame.check:
    description: Check the MOTD
    default: true
  motd.ingame.set:
    description: Uset he SetMOTD Command to change the MOTD.
    default: op
  motd.server.set:
    description: Uset he SetMOTD Command to change the MOTD.
    default: op