name: Kit
version: ${project.version}
main: com.nitecell.kit.Kit
api-version: 1.13
authors: [Nitecell]
description: Kit Command
depend: [Vault]

commands:
  clear:
    usage: /<command>
    aliases: [ci]
    description: Clear Inventory
  kit:
    usage: /<command>
    description: Kit Command